# Generated by Django 3.0.5 on 2020-07-15 20:43

import apps.budget.models.upload
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'ordering': ['country', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.budget.models.upload.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'txt'])], verbose_name='file')),
                ('report', models.CharField(choices=[('oge', 'OGE - Orçamento Geral do Estado'), ('reo', 'REO - Relatório de Execução Orçamentária'), ('cge', 'CGE - Conta Geral do Estado')], max_length=5, verbose_name='report')),
                ('status', models.CharField(choices=[('validating', 'Validating'), ('importing', 'Importing'), ('success', 'Success'), ('validation_error', 'Validation error'), ('import_error', 'Import error')], editable=False, max_length=20, verbose_name='status')),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, editable=False, size=None, verbose_name='errors')),
                ('log', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, editable=False, size=None, verbose_name='log')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='uploaded on')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget', verbose_name='budget')),
                ('uploaded_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('initial_budget_investment', models.FloatField(blank=True, null=True, verbose_name='initial budget for investment')),
                ('initial_budget_operation', models.FloatField(blank=True, null=True, verbose_name='initial budget for operation')),
                ('initial_budget_aggregated', models.FloatField(blank=True, null=True, verbose_name='initial budget')),
                ('budget_investment', models.FloatField(blank=True, null=True, verbose_name='updated budget for investment')),
                ('budget_operation', models.FloatField(blank=True, null=True, verbose_name='updated budget for operation')),
                ('budget_aggregated', models.FloatField(blank=True, null=True, verbose_name='updated budget')),
                ('execution_investment', models.FloatField(blank=True, null=True, verbose_name='execution for investment')),
                ('execution_operation', models.FloatField(blank=True, null=True, verbose_name='execution for operation')),
                ('execution_aggregated', models.FloatField(blank=True, null=True, verbose_name='execution')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='budget.Budget', verbose_name='budget')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.Function', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'function',
                'verbose_name_plural': 'functions',
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('initial_budget_investment', models.FloatField(blank=True, null=True, verbose_name='initial budget for investment')),
                ('initial_budget_operation', models.FloatField(blank=True, null=True, verbose_name='initial budget for operation')),
                ('initial_budget_aggregated', models.FloatField(blank=True, null=True, verbose_name='initial budget')),
                ('budget_investment', models.FloatField(blank=True, null=True, verbose_name='updated budget for investment')),
                ('budget_operation', models.FloatField(blank=True, null=True, verbose_name='updated budget for operation')),
                ('budget_aggregated', models.FloatField(blank=True, null=True, verbose_name='updated budget')),
                ('execution_investment', models.FloatField(blank=True, null=True, verbose_name='execution for investment')),
                ('execution_operation', models.FloatField(blank=True, null=True, verbose_name='execution for operation')),
                ('execution_aggregated', models.FloatField(blank=True, null=True, verbose_name='execution')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='budget.Budget', verbose_name='budget')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.Agency', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'agency',
                'verbose_name_plural': 'agencies',
            },
        ),
    ]
