# Generated by Django 3.0.5 on 2020-06-29 01:48

import common.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
            ],
            bases=(common.mixins.CountryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads', verbose_name='file')),
                ('report', models.CharField(choices=[('oge', 'Orçamento Geral do Estado'), ('reo', 'Relatório de Execução Orçamentária'), ('cge', 'Conta Geral do Estado')], max_length=5, verbose_name='report')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='upload time')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget', verbose_name='budget')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='upload by')),
            ],
            bases=(models.Model,),
        ),
    ]
