# Generated by Django 3.0.5 on 2020-07-15 23:45

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=djmoney.models.fields.CurrencyField(default='XYZ', max_length=3),
        ),
    ]
