# Generated by Django 3.0.5 on 2020-06-29 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20200502_2258'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='report',
            field=models.CharField(choices=[('oge', 'OGE - Orçamento Geral do Estado'), ('reo', 'REO - Relatório de Execução Orçamentária'), ('cge', 'CGE - Conta Geral do Estado')], max_length=5, verbose_name='report'),
        ),
    ]
