# Generated by Django 3.0.5 on 2020-06-29 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0002_auto_20200628_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='upload_by',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='uploaded on'),
            preserve_default=False,
        ),
    ]
