# Generated by Django 3.0.8 on 2020-12-04 22:45

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20201204_1945'),
        ('budget', '0003_auto_20200715_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'agency', 'verbose_name_plural': 'agencies data'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'function', 'verbose_name_plural': 'functional data'},
        ),
        migrations.AddField(
            model_name='agency',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='function',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='geo.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AOA', 'AOA Kz'), ('CVE', 'CVE $'), ('MZN', 'MZN MT'), ('STD', 'STD Db'), ('USD', 'USD $'), ('XOF', 'XOF (CFA)')], default='XYZ', editable=False, help_text='All values from budget presented in this currency', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='budget.Budget', verbose_name='budget'),
        ),
    ]
