# Generated by Django 3.0.5 on 2020-06-29 04:44

import apps.budget.models.upload
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20200629_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('validating', 'Validating'), ('importing', 'Importing'), ('success', 'Success'), ('validation_error', 'Validation error'), ('import_error', 'Import error')], default='success', editable=False, max_length=20, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to=apps.budget.models.upload.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'txt'])], verbose_name='file'),
        ),
    ]
