# Generated by Django 3.0.8 on 2020-12-09 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20201204_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='score_data_quality',
            field=models.SmallIntegerField(blank=True, help_text='0 - 200', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='score - data quality'),
        ),
        migrations.AddField(
            model_name='budget',
            name='score_open_data',
            field=models.SmallIntegerField(blank=True, help_text='0 - 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score - open data'),
        ),
        migrations.AddField(
            model_name='budget',
            name='score_reports',
            field=models.SmallIntegerField(blank=True, help_text='0 - 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score - reports'),
        ),
        migrations.AddField(
            model_name='budget',
            name='transparency_index',
            field=models.SmallIntegerField(blank=True, help_text='0 - 100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='transparency index'),
        ),
    ]
