# Generated by Django 3.0.5 on 2020-06-30 20:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20200630_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['country', '-year'], 'verbose_name': 'budget', 'verbose_name_plural': 'budgets'},
        ),
        migrations.AddField(
            model_name='upload',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='errors'),
        ),
        migrations.AddField(
            model_name='upload',
            name='log',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='log'),
        ),
    ]
