# Generated by Django 3.0.5 on 2020-07-02 16:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20200630_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='budget.Budget', verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='function',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='budget.Budget', verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None, verbose_name='errors'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='log',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None, verbose_name='log'),
        ),
    ]
