# Generated by Django 3.0.5 on 2020-07-02 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20200702_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, editable=False, size=None, verbose_name='errors'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='log',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, editable=False, size=None, verbose_name='log'),
        ),
    ]
