# Generated by Django 3.0.8 on 2021-02-09 22:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20210112_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='inferred_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='inferred values from siblings or descendants'),
        ),
        migrations.AddField(
            model_name='function',
            name='inferred_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='inferred values from siblings or descendants'),
        ),
    ]
