# Generated by Django 3.0.8 on 2021-02-12 02:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20210209_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='inferred_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='fields that were inferred (not originally inputted)'),
        ),
        migrations.AddField(
            model_name='budget',
            name='agency_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name="agency's execution"),
        ),
        migrations.AddField(
            model_name='budget',
            name='agency_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name="agency's execution"),
        ),
        migrations.AddField(
            model_name='budget',
            name='function_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name="function's budget"),
        ),
        migrations.AddField(
            model_name='budget',
            name='function_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name="function's execution"),
        ),
        migrations.AddField(
            model_name='function',
            name='inferred_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='fields that were inferred (not originally inputted)'),
        ),
    ]
