# Generated by Django 3.0.8 on 2021-02-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_transparencyindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='score_data_quality',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='score_open_data',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='score_reports',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='transparency_index',
        ),
    ]
