# Generated by Django 3.0.8 on 2021-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_uploadlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadlog',
            options={'verbose_name': 'upload log', 'verbose_name_plural': 'uploads log'},
        ),
        migrations.RemoveField(
            model_name='upload',
            name='log',
        ),
        migrations.AlterField(
            model_name='uploadlog',
            name='log_type',
            field=models.CharField(choices=[('new_category', 'new category'), ('update', 'update')], editable=False, max_length=20, verbose_name='log type'),
        ),
    ]
