# Generated by Django 3.0.8 on 2021-05-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20210218_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-budget_aggregated'], 'verbose_name': 'agency', 'verbose_name_plural': 'agencies data'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['-budget_aggregated'], 'verbose_name': 'function', 'verbose_name_plural': 'functional data'},
        ),
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This budget will only be included on site if this option is checked.', verbose_name='active'),
        ),
    ]
