# Generated by Django 3.0.8 on 2021-07-30 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_auto_20210518_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='updated on'),
            preserve_default=False,
        ),
    ]
