# Generated by Django 3.0.8 on 2021-07-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_auto_20210715_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_functional_budget', models.FloatField(blank=True, editable=False, null=True, verbose_name='expenses budget on functions')),
                ('expense_functional_execution', models.FloatField(blank=True, editable=False, null=True, verbose_name='expenses execution on functions')),
                ('expense_organic_budget', models.FloatField(blank=True, editable=False, null=True, verbose_name='expenses budget on agencies')),
                ('expense_organic_execution', models.FloatField(blank=True, editable=False, null=True, verbose_name='expenses execution on agencies')),
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='budget.Budget', verbose_name='budget')),
            ],
            options={
                'verbose_name': 'budget aggregated',
                'verbose_name_plural': 'budget aggregated values',
            },
        ),
    ]
