# Generated by Django 3.0.8 on 2021-07-15 21:08

import dirtyfields.dirtyfields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_budgetsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='code')),
                ('initial_budget_investment', models.FloatField(blank=True, null=True, verbose_name='initial budget for investment')),
                ('initial_budget_operation', models.FloatField(blank=True, null=True, verbose_name='initial budget for operation')),
                ('initial_budget_aggregated', models.FloatField(blank=True, null=True, verbose_name='initial budget')),
                ('budget_investment', models.FloatField(blank=True, null=True, verbose_name='updated budget for investment')),
                ('budget_operation', models.FloatField(blank=True, null=True, verbose_name='updated budget for operation')),
                ('budget_aggregated', models.FloatField(blank=True, null=True, verbose_name='updated budget')),
                ('execution_investment', models.FloatField(blank=True, null=True, verbose_name='execution for investment')),
                ('execution_operation', models.FloatField(blank=True, null=True, verbose_name='execution for operation')),
                ('execution_aggregated', models.FloatField(blank=True, null=True, verbose_name='execution')),
                ('inferred_values', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='inferred values from siblings or descendants')),
                ('inferred_fields', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='fields that were inferred (not originally inputted)')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('group', models.CharField(choices=[('nature', 'Nature'), ('source', 'Source')], max_length=30, verbose_name='group')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='budget.Budget', verbose_name='budget')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.Revenue', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'revenue',
                'verbose_name_plural': 'revenues',
                'ordering': ['-budget_aggregated'],
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
