# Generated by Django 3.0.8 on 2021-07-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_revenue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsummary',
            options={'verbose_name': 'budget summary', 'verbose_name_plural': 'budget aggregated values'},
        ),
        migrations.AddField(
            model_name='budgetsummary',
            name='revenue_nature_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total revenues budget (nature)'),
        ),
        migrations.AddField(
            model_name='budgetsummary',
            name='revenue_nature_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total revenues execution (nature)'),
        ),
        migrations.AddField(
            model_name='budgetsummary',
            name='revenue_source_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total revenues budget (source)'),
        ),
        migrations.AddField(
            model_name='budgetsummary',
            name='revenue_source_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total revenues execution (source'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='expense_functional_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total expenses budget (functional)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='expense_functional_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total expenses execution (functional)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='expense_organic_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total expenses budget (organic)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='expense_organic_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='total expenses execution (organic)'),
        ),
    ]
