# Generated by Django 3.0.8 on 2021-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_auto_20210715_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsummary',
            options={'verbose_name': 'budget summary', 'verbose_name_plural': 'aggregated values'},
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='expense_functional_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='expenses budget (functional)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='expense_functional_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='expenses execution (functional)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='expense_organic_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='expenses budget (organic)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='expense_organic_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='expenses execution (organic)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='revenue_nature_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='revenues budget (nature)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='revenue_nature_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='revenues execution (nature)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='revenue_source_budget',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='revenues budget (source)'),
        ),
        migrations.AlterField(
            model_name='budgetsummary',
            name='revenue_source_execution',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='revenues execution (source)'),
        ),
    ]
