# Generated by Django 3.0.8 on 2021-07-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('budget', '0020_auto_20210725_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='expense',
            name='object_id',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
