# Generated by Django 3.0.8 on 2021-08-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_auto_20210729_1116'),
        ('budget', '0016_upload_updated_on'),
    ]

    operations = [
    ]
