# Generated by Django 3.0.8 on 2021-08-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('budget', '0022_merge_20210802_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='function',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='agency_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='agency_execution',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='function_budget',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='function_execution',
        ),
        migrations.AlterField(
            model_name='expense',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Function',
        ),
    ]
