# Generated by Django 3.0.8 on 2021-10-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_auto_20210811_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='output_file',
            field=models.FileField(blank=True, editable=False, help_text='Auto generated CSV file with all data from budget.', null=True, upload_to='exports', verbose_name='output file.'),
        ),
    ]
