# Generated by Django 3.0.8 on 2021-10-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_auto_20211026_1238'),
        ('budget', '0024_auto_20211024_1758'),
    ]

    operations = [
    ]
