# Generated by Django 3.1.10 on 2026-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_merge_20211027_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencyindex',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports', verbose_name='report'),
        ),
    ]
