# Generated by Django 3.1.10 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_transparencyindex_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('title_pt', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/files', verbose_name='file')),
                ('file_pt', models.FileField(blank=True, null=True, upload_to='attachments/files', verbose_name='file')),
                ('file_en', models.FileField(blank=True, null=True, upload_to='attachments/files', verbose_name='file')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='attachments/thumbnails', verbose_name='thumbnail')),
                ('thumbnail_pt', models.ImageField(blank=True, null=True, upload_to='attachments/thumbnails', verbose_name='thumbnail')),
                ('thumbnail_en', models.ImageField(blank=True, null=True, upload_to='attachments/thumbnails', verbose_name='thumbnail')),
                ('is_visible', models.BooleanField(default=True, verbose_name='is visible')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ['id'],
            },
        ),
    ]
