# Generated by Django 3.1.10 on 2026-05-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencyindex',
            name='report_en',
            field=models.FileField(blank=True, null=True, upload_to='results', verbose_name='results report'),
        ),
        migrations.AddField(
            model_name='transparencyindex',
            name='report_pt',
            field=models.FileField(blank=True, null=True, upload_to='results', verbose_name='results report'),
        ),
        migrations.AlterField(
            model_name='transparencyindex',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='results', verbose_name='results report'),
        ),
    ]
