# Generated by Django 3.1.10 on 2026-09-10 20:27

from django.db import migrations, models


def set_initial_attachment_order(apps, schema_editor):
    Attachment = apps.get_model('budget', 'Attachment')
    for index, attachment in enumerate(Attachment.objects.order_by('id'), start=1):
        attachment.order = index
        attachment.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_auto_20260523_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='order'),
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={
                'ordering': ['order', 'id'],
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
            },
        ),
        migrations.RunPython(set_initial_attachment_order, migrations.RunPython.noop),
    ]
