# Generated by Django 3.0.5 on 2020-07-16 00:02

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=djmoney.models.fields.CurrencyField(choices=[('AOA', 'AOA Kz'), ('CVE', 'CVE $'), ('MZN', 'MZN MT'), ('STD', 'STD Db'), ('USD', 'USD $'), ('XOF', 'XOF (CFA)')], default='XYZ', max_length=3),
        ),
    ]
