# Generated by Django 3.0.5 on 2020-05-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
    ]
